---
title: Awesome
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
excerpt_separator: ''
pygments: true
markdown: kramdown
url: http://ableton79.github.io
email: 
author: ableton79
description: My awesome new site
paginate: 3
google_analytics: 
